config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'foods#index'
  resources :foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all

  end

  def new
    @food = Food.new
  end

  def create
    Food.create(food_params)
    redirect_to root_path
  end

  def food_params
    params.require(:food).permit(:name, :food)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<h1>Enter Your Name and favourite food by clicking

<%= link_to new_food_path do %>
     Here
   <% end %>
</h1>

<h1>Our users favourite foods are:</h1>

<% @foods.each do |food| %>
  <div>
    <h1><%= food.name %></h1><br />
    <i><%= food.food %></i><br />
  </div>

  <hr />
<% end %>

app/views/foods/new.html.erb
<h1>Enter Your Favourite food and name below!</h1>
<%= simple_form_for @food do |f| %>
    <%= f.input :name %>
    <%= f.input :food %>
    <%= f.submit 'Create' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>